withastro/adapters

.changeset/grumpy-windows-cross.md
packages/cloudflare/CHANGELOG.md
packages/cloudflare/package.json
packages/netlify/CHANGELOG.md
packages/netlify/package.json

This reverts commit ed73c9d56038695e03338545a46781a7626ec277.

Revert "[ci] release (#16)"

---

packages/test-utils/package.json

fix(test-utils): missing package version

---

.changeset/grumpy-windows-cross.md
packages/cloudflare/CHANGELOG.md
packages/cloudflare/package.json
packages/netlify/CHANGELOG.md
packages/netlify/package.json

revert: "[ci] release"

---

.eslintignore
.github/workflows/release.yml
pnpm-lock.yaml
pnpm-workspace.yaml
scripts/jsconfig.json
scripts/notify/index.js
scripts/package.json

chore: add script to generate discord release notification

---

.changeset/chilled-plants-move.md
packages/cloudflare/src/index.ts

- I forgot to also configure persistence dir for `cache`

fix(cloudflare): missing persistence config for `cache`

---

.changeset/hot-wolves-lick.md
packages/cloudflare/src/index.ts

should fix https://discord.com/channels/830184174198718474/1164502377215307867

fix(cloudflare): adapter breaks if no args passed

---

.github/workflows/snapshot-release.yml

- fixes snapshot release workflow

fix: snapshot release workflow

---

.github/workflows/snapshot-release.yml

- tries to fix the preview release workflow

fix: snapshot release workflow repo fetch-depth

---

.github/workflows/snapshot-release.yml

- try to fix issue that main is not checked out

fix: snapshot release main branch not found

---

.github/workflows/format.yml

revert: shared format workflow

---

.changeset/modern-garlics-explain.md
packages/cloudflare/src/index.ts

- fix a regression which breaks builds
- running manually on a repro provided from cloudflare team
- changeset

fix(astro): build regression

---

.changeset/fast-beans-check.md
packages/cloudflare/package.json
packages/netlify/package.json
pnpm-lock.yaml

chore: update deps

---

.github/workflows/discord.yml

- adds CI workflow for Congratsbot

chore: add Congratsbot

---

.changeset/loud-coins-begin.md
packages/cloudflare/package.json
packages/netlify/package.json

- update `peerDependencies` to be more wide, and in sync with astro core repo

fix: peerDependency definition

---

.changeset/config.json

chore: fix changeset

---

.changeset/breezy-rings-invite.md
.changeset/good-plums-guess.md
.changeset/loud-coins-begin.md
.changeset/sour-beers-begin.md
packages/cloudflare/CHANGELOG.md
packages/cloudflare/package.json

revert "[ci] release"

---

.changeset/stale-boats-joke.md
packages/netlify/test/functions/fixtures/base64-response/src/pages/font.js
packages/netlify/test/functions/fixtures/base64-response/src/pages/image.js
packages/netlify/test/functions/fixtures/cookies/src/pages/login.js
packages/netlify/test/functions/fixtures/split-support/src/env.d.ts

updated tests to use uppercase methods

fix(netlify): tests

---

.changeset/clever-eagles-search.md
packages/netlify/README.md

Updates the Netlify README similar to the Cloudflare one.
Just docs
All docs

Update Netlify README.md

---

.changeset/cold-meals-roll.md
packages/cloudflare/package.json
pnpm-lock.yaml

Reverts withastro/adapters#122

Revert "Bumped miniflare version to avoid CVE-2023-7078"

---

.changeset/cold-meals-roll.md
packages/cloudflare/package.json
pnpm-lock.yaml

Bumped miniflare version to avoid CVE-2023-7078

---

.changeset/curly-oranges-end.md
packages/cloudflare/package.json
packages/cloudflare/test/fixtures/dev-runtime-pages/package.json
packages/cloudflare/test/fixtures/dev-runtime-workers/package.json
packages/cloudflare/test/fixtures/directory-mode/package.json
packages/cloudflare/test/fixtures/external-image-service/package.json
packages/cloudflare/test/fixtures/function-per-route/package.json
packages/cloudflare/test/fixtures/hybrid/package.json
packages/cloudflare/test/fixtures/no-output/package.json
packages/cloudflare/test/fixtures/prerender/package.json
packages/cloudflare/test/fixtures/routes-json/package.json
packages/cloudflare/test/fixtures/wasm-directory/package.json
packages/cloudflare/test/fixtures/wasm-function-per-route/package.json
packages/cloudflare/test/fixtures/wasm/package.json
packages/cloudflare/test/fixtures/with-solid-js/package.json
packages/cloudflare/test/fixtures/wrangler-runtime/package.json
packages/netlify/test/functions/fixtures/middleware/package.json
pnpm-lock.yaml

- bumps Astro versions
- needed for pending major release

updates Astro core version

---

.changeset/big-ads-care.md
packages/cloudflare/src/index.ts
packages/cloudflare/src/utils/deduplicatePatterns.ts
packages/cloudflare/test/routes-json.test.js

fix(cloudflare): duplicate patterns in `_routes.json`

---

.changeset/eleven-books-push.md
packages/cloudflare/src/utils/local-runtime.ts

- closes #151 
- existing tests
- no docs needed

fix(cloudflare): error if cacheDir already exists

---

.github/workflows/format.yml

fix: format workflow

---

.changeset/flat-pears-hug.md
packages/cloudflare/src/index.ts

- Preparation of v10 https://github.com/withastro/adapters/pull/159
- I'm planning to release v10 next week

chore(cloudflare): add deprecated tags

---

.changeset/itchy-ears-jam.md
packages/cloudflare/src/index.ts

- closes https://github.com/withastro/adapters/issues/209
- manual tested + existing solid test
- bug fix, no docs needed

fixes solid

---

.changeset/lazy-pears-jam.md
.changeset/nice-carpets-destroy.md
packages/cloudflare/src/utils/generate-routes-json.ts
packages/cloudflare/test/routes-json.test.js

- closes https://github.com/withastro/adapters/issues/216
- manually and commented reason behind the change, no tests needed
- bug fix, no docs needed

fix(cloudflare): route generation exclude wildcard

---

packages/cloudflare/test/_test-utils.js
packages/cloudflare/test/no-output.test.js

Super tiny improvements in the tests that I found while working on another PR.

chore(cloudflare): minor test improvements

---

.changeset/stupid-houses-laugh.md
packages/cloudflare/src/index.ts
packages/cloudflare/src/utils/image-config.ts

- Added a new imageService option to cloudflare integraion: `custom`
- Closes: #228 
No Tests
- https://github.com/withastro/docs/pull/7813

Add imageService 'custom' to cloudflare integration

---

.changeset/shaggy-geckos-jam.md
packages/cloudflare/src/utils/index.ts

fix(cloudflare): removes log

---

.changeset/thirty-apricots-marry.md
packages/cloudflare/src/utils/generate-routes-json.ts
packages/cloudflare/test/routes-json.test.js

- fixes order for `_routes.json` generation
- existing tests
- bug fix, no docs needed

fix(cloudflare): routes.json order

---

.changeset/twenty-terms-bathe.md
packages/cloudflare/package.json
packages/cloudflare/src/entrypoints/server.ts
packages/cloudflare/test/astro-env.test.js
packages/cloudflare/test/fixtures/astro-env/package.json
packages/netlify/src/ssr-function.ts
pnpm-lock.yaml

- port of https://github.com/withastro/astro/pull/11261
- existing
- bugfix not needed

fix: backward compatibility Astro <= 4.9

---

.changeset/hot-swans-doubt.md
packages/netlify/src/index.ts
packages/netlify/src/ssr-function.ts

- Uses the rollup trick
N/A
N/A

fix(netlify): astro:env getSecret

---

.changeset/old-dolls-double.md
packages/cloudflare/src/index.ts

- closes https://github.com/withastro/adapters/issues/300
- no new test needed
- no docs update needed

fix(cloudflare): wrangler.toml error

---

.github/workflows/event-dispatch.yml

ci: build whole repo due to interconnected deps

---

.github/workflows/event-dispatch.yml

chore: build whole repo due to interconnected deps

---

.changeset/flat-dolls-nail.md
.changeset/pre.json
packages/node/package.json
packages/vercel/package.json

feat: enter beta mode

---

scripts/notify/index.js

- this should fix the notification script
- existing
- not needed

chore: fix release notification step

---

.github/workflows/release.yml

This PR adds `legacy` to the deployable branches
CI should pass
N/A

ci: add `legacy` to the deployable branches

---

.changeset/config.json
.changeset/pre.json

This PR exits pre-mode
CI should pass
N/A

chore: exit pre-mode

---

packages/node/src/serve-static.ts
packages/node/test/node-middleware.test.js
packages/vercel/test/edge-middleware.test.js
scripts/notify/index.js

This PR refactor a nasty `switch/case` that was difficult to read. I didn't like the intentional fallthrough, because it makes things less portable and difficult to understand (personal preference).
CI should pass
N/A

refactor: readability

---

.changeset/shy-bananas-wait.md
package.json
packages/cloudflare/package.json
packages/cloudflare/src/index.ts
packages/cloudflare/test/fixtures/with-svelte/astro.config.mjs
packages/cloudflare/test/fixtures/with-svelte/package.json
packages/cloudflare/test/fixtures/with-svelte/src/components/Component.svelte
packages/cloudflare/test/fixtures/with-svelte/src/pages/index.astro
packages/cloudflare/test/with-svelte.test.js
packages/netlify/package.json
pnpm-lock.yaml

fix https://github.com/withastro/adapters/issues/461
fix https://github.com/withastro/adapters/issues/410
supersedes https://github.com/withastro/adapters/pull/462, @avanderbergh I created a new PR since it's easier to fix this for both issues, but thanks for creating the PR there.
Update the conditions setup in ssr environments according to Vite 6's breaking change: https://vite.dev/guide/migration.html#default-value-for-resolve-conditions
Existing tests should pass.
I also added a new svelte test for cloudflare. Also unskipped the solid tests.
n/a. bug fix.

Fix cloudflare ssr conditions setup

---

packages/node/test/preview-host.test.js

I missed this commit from #514 where I added tests

chore(node): add tests for preview host
