.changeset/rich-foxes-deliver.md, packages/cloudflare/.gitignore, packages/cloudflare/README.md, packages/cloudflare/src/index.ts, packages/cloudflare/test/fixtures/dev-runtime/astro.config.mjs, packages/cloudflare/test/fixtures/dev-runtime/package.json, pnpm-lock.yaml
- Fixes a DX issue with Cloudflare runtime in `astro dev`
- Now you should be able to use `wrangler` as you are used to, to seed db or apply migrations
- **Open question:** see code comments of self-review
- existing test
- cc @withastro/maintainers-docs
=> chore(cloudflare): add option to set persistence dir

.github/workflows/format.yml, .github/workflows/snapshot-release.yml
- use shared `format` workflow
- ported `preview` workflow, due to different secret names
=> chore: update CI/CD workflows

.changeset/nice-impalas-whisper.md, packages/cloudflare/src/index.ts
- this fixes a regression introduced 
- related to https://github.com/withastro/astro/pull/8880
- for details see messages after: https://discord.com/channels/830184174198718474/845430950191038464/1165031078722011238
=> fix(cloudflare): astro asset image service

packages/netlify/test/functions/redirects.test.js
Fix incorrect assertion. Inside the try block, the assertion is intentionally failing to fail the test, however because it's still within the try block, the catch block will turn it back to passing, which is incorrect.
Ran the tests manually. Found this while working on https://github.com/withastro/astro/issues/7889
n/a
=> Fix incorrect netlify redirect test

packages/netlify/test/functions/base.test.js, packages/netlify/test/functions/fixtures/base/astro.config.mjs, packages/netlify/test/functions/fixtures/base/package.json, packages/netlify/test/functions/fixtures/base/src/env.d.ts, packages/netlify/test/functions/fixtures/base/src/pages/index.astro, pnpm-lock.yaml
- Add fixture folder
Prepared test as well but commented out the failing part
N/A
cc @alexanderniebuhr
=> test(netlify): add base fixture and prepare test (#45)

.changeset/twelve-grapes-dream.md, packages/cloudflare/src/entrypoints/server.advanced.ts, packages/cloudflare/src/entrypoints/server.directory.ts
Turns out it was an adapter issue after all! Fixes withastro/adapters#67
Currently, missing routes in the Cloudflare adapter are responded to with blank 404 responses:
```js
return new Response(null, {
status: 404,
statusText: 'Not found',
});
```
Astro has its own error handler! We can use that by returning `undefined` for our `routeData` in our render function. This pr does that.
By using `pnpm link` in the [latest](https://github.com/ToxiWoxi/astro-404-issue/tree/latest) branch of my 404 issue repo and going to `http://localhost:8788/thispagedoesnotexist` in my browser, I can confirm that these changes result in the #renderError method being invoked which allows 404 pages being rendered properly whether they're prerendered or server-rendered.
I've also set up 3 previews:
One that uses …
=> fix(cloudflare): Fix `404.astro` not being used when `routes.strategy` is set to `exclude`

.changeset/spotty-kings-roll.md, packages/cloudflare/src/index.ts
- always use `exclude` strategy for `auto`, to make sure routing works as expected on Cloudflare's SPA mode
- closes https://github.com/withastro/adapters/issues/64
=> fix(cloudflare): routing strategy doesn't support on-demand 404

packages/netlify/README.md
- This PR fixes broken links in Netlify README
- Please see [withastro/docs#5504](https://github.com/withastro/docs/issues/5504) for background context
- No tests added as these changes appear to be related to typos
- This PR fixes broken links in Netlify README
=> Fix broken links in Netlify README

.changeset/violet-zoos-push.md, packages/cloudflare/test/fixtures/wasm-directory/src/pages/index.ts, packages/cloudflare/test/fixtures/wasm-function-per-route/src/pages/deeply/nested/route.ts, packages/cloudflare/test/fixtures/wasm-function-per-route/src/pages/index.ts, packages/cloudflare/test/fixtures/wasm/src/pages/add/[a]/[b].ts, packages/cloudflare/test/fixtures/wasm/src/pages/hybrid.ts
I notice this when playing with Astro v4.0.0-beta.4. I think this should only be an issue when Astro 4 is in. But as of now the tests still passes. I'd say it's to push this along when updating tests to Astro v4. I'll leave as a draft PR for reference.
This only happens when a test fixture is updated to v4
- More context on https://github.com/withastro/adapters/issues/76#issuecomment-1837365310
Now, I'm unsure just removing it is the solution. This change is based on the mentioned upstream Astro PR and from it, it seems that just removing is fine.
- Removed `type EndpointOutput`
`pnpm test` on Windows.
It should not affect users
---
Thank you
=> chore: remove `type EndpointOutput`

.changeset/breezy-rings-invite.md, packages/cloudflare/src/index.ts
closes https://github.com/withastro/adapters/issues/76
=> chore(cloudflare): remove deprecated `build.split` option

.changeset/config.json
=> fix: try another changeset config

.changeset/fluffy-spoons-cheat.md, packages/netlify/src/index.ts
Closes https://github.com/withastro/adapters/issues/104.
We were crashing when importing the adapter because importing JSON isn't supported on all versions of Node.js. This PR replaces it with `readFile` instead. We could've used import assertions instead, but then we'd also need to change some typescript settings which is risky.
tested locally.
no docs needed, it's a fix.
=> fix: use fs read instead of JSON import

.changeset/cold-meals-roll.md, packages/cloudflare/package.json, pnpm-lock.yaml
Bumped miniflare version (3.20231025.1 --> 3.20231030.2)
https://github.com/advisories/GHSA-fwvg-2739-22v7
No changes to the package itself and the fixes to miniflare should not affect this adapter.
No docs update is needed as this PR only fixes that annoying npm vuln warning
=> Bumped miniflare version to avoid CVE-2023-7078

.changeset/dry-rules-bathe.md, packages/netlify/src/ssr-function.ts
If `cacheOnDemandPages` is enabled, we're currently adding caching headers to all responses, including POST responses. Caching POST requests is unconventional, and shouldn't be done by default!
This PR makes it so the adapter only adds caching headers for GET and HEAD requests.
No test added because there's no test for `cacheOnDemandPages` yet - let me know if I should add one.
Don't think this needs docs.
=> fix(netlify): only cache GET/HEAD methods

.changeset/curly-oranges-end.md, packages/cloudflare/package.json, packages/cloudflare/src/entrypoints/server.advanced.ts, packages/cloudflare/src/entrypoints/server.directory.ts, packages/netlify/package.json, packages/netlify/src/ssr-function.ts
- Updates the app.redner call to use the latest signature
- runs the existing unit test
=> fix: updates to use the new app.render call signature

.changeset/seven-comics-act.md
- adds the already approved changeset for netlify but with `4.0.0` instead of `4.2.0`
=> chore: add changeset for netlify

.changeset/curly-oranges-end.md, .changeset/seven-comics-act.md, packages/netlify/package.json, packages/netlify/test/hosted/hosted-astro-project/package.json, packages/test-utils/package.json, pnpm-lock.yaml
- also bump Astro to `^4.2.0` for Netlify
=> chore: bump astro version

.changeset/serious-kids-suffer.md, packages/netlify/src/index.ts, packages/netlify/src/ssr-function.ts, packages/netlify/test/functions/cookies.test.js, packages/netlify/test/functions/fixtures/cookies/src/pages/404.astro, packages/netlify/test/functions/fixtures/redirects/src/pages/404.astro, packages/netlify/test/functions/redirects.test.js
Adds tests around 404 pages. Fixes prerendered 404 pages by embedding them into the SSR Handler and returning it when no route matches. There's other solutions to this, as we're discussing in https://github.com/withastro/adapters/issues/133, but this is a quick & easy fix to get 404 pages functioning.
added two unit tests.
It's a fix, so no docs needed. Related to https://github.com/withastro/adapters/issues/133.
=> fix(netlify): pre-rendered 404 pages aren't shown

.changeset/odd-shoes-talk.md, packages/netlify/src/index.ts, packages/netlify/src/ssr-function.ts, packages/netlify/test/functions/fixtures/split-support/src/env.d.ts
- Ensures that when `edgeMiddleware` is enabled, only the edge middleware can call the internal serverless function.
Manual
- https://github.com/withastro/docs/pull/6786
=> feat(netlify): verification for edge middleware

.changeset/large-fireants-wink.md, packages/netlify/src/ssr-function.ts, packages/netlify/test/functions/redirects.test.js
Addresses https://github.com/withastro/adapters/pull/143#issuecomment-1934727870
We're serving the prerendered 404 page with the default content-type, which is `text/plain`. This leads browser to showing the contents of the page as source code, instead of rendering it!
The fix is to set the content-type to `text/html`. Doh!
extended a test.
it's a bugfix, no docs update needed.
=> fix(netlify): serve prerendered 404 page with content-type: text/html

.changeset/red-trains-tease.md, packages/cloudflare/package.json, packages/cloudflare/test/fixtures/dev-runtime-pages/package.json, packages/cloudflare/test/fixtures/dev-runtime-workers/package.json, packages/cloudflare/test/fixtures/directory-mode/package.json, packages/cloudflare/test/fixtures/external-image-service/package.json, packages/cloudflare/test/fixtures/function-per-route/package.json, packages/cloudflare/test/fixtures/hybrid/package.json, packages/cloudflare/test/fixtures/no-output/package.json, packages/cloudflare/test/fixtures/prerender/package.json, packages/cloudflare/test/fixtures/routes-json/package.json, packages/cloudflare/test/fixtures/wasm-directory/package.json, packages/cloudflare/test/fixtures/wasm-function-per-route/package.json, packages/cloudflare/test/fixtures/wasm/package.json, packages/cloudflare/test/fixtures/with-solid-js/package.json, packages/cloudflare/test/fixtures/wrangler-runtime/package.json, packages/netlify/package.json, packages/netlify/src/index.ts, packages/netlify/test/functions/edge-middleware.test.js, packages/netlify/test/hosted/hosted-astro-project/package.json, packages/test-utils/package.json, pnpm-lock.yaml
- Updates astro 4.2.0 to 4.3.5 to see if builds fail because of `cssesc`. (Edit: womp womp)
- Fixes one of the two errors brought up in https://github.com/withastro/astro/issues/9880
Existing tests should pass.
Does not affect usage
=> fix(netlify): consider main fields when bundling

.changeset/young-ravens-hammer.md, packages/netlify/src/index.ts
This is a drive by change because `randomUUID` is not on the global version of `crypto` on my node version (`v18.18.2`). I'm uncertain if this breaks any compatibility for others and do not have pnpm to run and commands.
Not testing done because this is a trivial change and don't have pnpm
Trivial change, probably should be noted in changelog
=> fix(netlify): replace `global.crypto` with `crypto`

.changeset/sharp-cameras-rescue.md, packages/cloudflare/src/utils/deduplicatePatterns.ts, packages/cloudflare/test/routes-json.test.js
- this should fix the deduplication error we had for more complex route definitions
- this is a fix for v9 of the adapter, in v10 we will refactor the complete route generation logic _(so this has a limited time to live)_
- also reverting change in test file https://github.com/withastro/adapters/pull/137/files#diff-d3130bfe10263d21a437f7e826fc4594ffc77e5cc37be1b09b10f5553b08c3ed
- closes https://github.com/withastro/adapters/issues/149
- I personally don't think it is worth to add a complete fixture for such edge-case, however we can if anyone has strong opinions
- Let's investigate if we can add unit tests instead which test only util functions
=> fix(cloudflare): _routes.json deduplication

.changeset/nervous-hotels-develop.md, packages/cloudflare/src/tmp-types.d.ts, packages/cloudflare/src/utils/local-runtime.ts, packages/cloudflare/test/dev-runtime-workers.test.js, packages/cloudflare/test/fixtures/dev-runtime-pages/astro.config.ts, packages/cloudflare/test/fixtures/dev-runtime-pages/src/pages/services.astro, packages/cloudflare/test/fixtures/dev-runtime-workers/src/pages/services.astro, packages/cloudflare/test/fixtures/dev-runtime-workers/wrangler.toml, packages/cloudflare/test/z-dev-runtime-pages.test.js
- This change introduces [Service bindings](https://developers.cloudflare.com/workers/configuration/bindings/about-service-bindings/) to the `@astrojs/cloudflare` adapter.
- Both setting the service bindings via `astro.config.ts` (`pages` type) and reading them from `wrangler.toml` (`workers` type) have been implemented.
Changes have been tested by updating the `dev-runtime-pages` and `dev-runtime-workers` fixtures and adding an integration test to `z-dev-runtime-pages.test.js` and `dev-runtime-workers.test.js` respectively.
Since this is a feature, it does not affect current users, but the [documentation](https://docs.astro.build/en/guides/integrations-guide/cloudflare/) will need to be updated.
closes #175
=> feat(cloudflare): add service bindings

.changeset/nine-lamps-cry.md, packages/netlify/src/index.ts, packages/netlify/test/functions/fixtures/middleware/astro.config.mjs, packages/netlify/test/functions/image-cdn.test.js, packages/netlify/test/hosted/hosted-astro-project/astro.config.mjs, packages/netlify/test/hosted/hosted-astro-project/netlify.toml, packages/netlify/test/hosted/hosted-astro-project/src/pages/index.astro
Previously the Netlify adapter was not able to enable support for remote images. This PR adds support for `image.remotePatterns` and `images.domains` config options. If a user sets these then the adapter converts them into regexes and writes them to Netlify's `images.remote_images` config option.
Added a test image to the fixture site. Added tests for generating the patterns and the config file.
Docs PR: https://github.com/withastro/docs/pull/7375
=> feat(netlify): add support for image.remotePatterns and images.domains with Netlify Image CDN

.changeset/strange-eels-smell.md, packages/cloudflare/src/utils/local-runtime.ts
Very minor, just a typo fix as I noticed it locally 🙂
=> fix(cloudflare): fix typo in .dev.vars log message

.changeset/selfish-spoons-mix.md, packages/cloudflare/package.json, packages/cloudflare/src/entrypoints/server.ts, packages/cloudflare/src/index.ts
- renames server entry
- deletes old exports definition
- updates `locals.runtime` API in production to match development
- existing tests
- bug fix of already documented behavior, no new docs needed
=> fix(cloudflare): align runtime api

packages/cloudflare/src/index.ts
we need to plugins so we can use `generateBundle` twice. Any other hook doesn't have file names with hashes already, and using `writeBundle` would need `fs` operation, which I think is worse.
`regex` is scary, but I'm not sure if it is worth to create an ast and convert back to string again
=> workaround prerender in pageMap

.changeset/silent-kings-matter.md, packages/cloudflare/src/index.ts, packages/cloudflare/src/utils/index.ts, packages/cloudflare/src/utils/non-server-chunk-detector.ts
- if the plugin runs for `client` it overrides, `nonServerChunks` with an empty array, leading to not removing the unused chunks
- closes https://github.com/withastro/adapters/issues/245
- closes https://github.com/withastro/adapters/issues/244
- I was not able to figure out why the existing tests didn't catch this, might be a super edge case 🤔 
- internal
- bug-fix
- no docs needed
=> fix(cloudflare): don't cleanup client bundle

.changeset/wet-dragons-count.md, packages/netlify/src/index.ts
Netlify Edge Functions don't define `process.env`, but Vite uses it for any code that accesses `import.meta.env`. This PR imports the Deno `node:process` polyfill at the top of the bundled  middleware edge function
Fixes https://github.com/withastro/adapters/issues/254
Tested with repro site https://github.com/jamesarosen/astro-broken-middleware-demo
=> fix(netlify): shim process.env in edge middleware

.changeset/yellow-cooks-hunt.md, packages/netlify/src/index.ts
The adapter adds an `included_files` option to the SSR function manifest to ensure that all traced files are included in the bundle. The path is currently relative to the root of the site, which breaks when in a monorepo. This PR changes the path to be absolute, which works everywhere. Using an absolute path is fine because bundling always happens on the same machine as the build.
Fixes #309 
Test deploy: https://66826aaccd6edbca0c286764--fascinating-belekoy-dfd085.netlify.app/
=> fix: use absolute path for included files

.changeset/shy-ties-float.md, packages/netlify/package.json, packages/netlify/src/index.ts, pnpm-lock.yaml
Astro 4.11 had a regression that caused edge middleware bundling to fail on Netlify in some situations. This seems to have been a side effect of something being imported into middleware that used astro:assets, which meant that sharp became a dependency. Sharp uses lots of node builtins, which aren't compatible with middleware, so builds were failing.
This PR sets sharp to "external", ensuring it's never bundled. In future we should think about ways to avoid these kinds of cross-runtime imports happening.
A test was failing that is now fixed
=> fix(netlify): externalise sharp when bundling edge middleware

.changeset/chilled-beers-hear.md, packages/netlify/src/index.ts, packages/netlify/test/functions/cookies.test.js, packages/netlify/test/functions/edge-middleware.test.js, packages/netlify/test/functions/image-cdn.test.js, packages/netlify/test/functions/redirects.test.js
Updates the Netlify adapter to use the upcoming Frameworks API.
Tests updated.
Internal change, no user-facing changes are expected.
=> feat: use Netlify Frameworks API

.github/workflows/snapshot-release.yml
Updates the snapshot action to allow all users with write access to publish snapshots, rather than just admins. This matches the behaviour in the main monorepo.
=> chore(actions): allow users with write access to publish preview releases

.changeset/ten-chicken-provide.md, packages/netlify/src/index.ts, packages/netlify/test/static/fixtures/redirects/astro.config.mjs, packages/netlify/test/static/headers.test.js
Adds immutable cache headers for everything in the assets directory. This is safe because they all have hashed filenames
Added a test, and manually checked a deployed site
=> feat(netlify): set cache headers for assets

.changeset/smooth-frogs-rush.md, packages/cloudflare/package.json, pnpm-lock.yaml
`@inox-tools/astro-when` 0.2.0 has a peer dependency requirement on Astro `^4.12.2` while the Cloudflare adapter has a peer dependency on `^4.10`. This could cause issues for people trying to update the adapter with Astro version 4.10.x and 4.11.x.
Astro When doesn't require anything from 4.12; it had that requirement just by using the same as all other Inox Tools. I released version 0.2.1 with the restriction relaxed to `^4`. Since the dependency on Astro When is `^0.2.0` consumer projects will already get the update, but I think it is safer to enforce the minimal correct version on the dependency.
=> fix(cloudflare): Fixes peer dependency conflict

.changeset/thirty-panthers-wave.md, packages/netlify/src/index.ts, packages/netlify/src/ssr-function.ts
- Same change we made to the Node adapter earlier.
- Prevents race condition where `crypto` could be used before the polyfill is applied.
- Tested via the server-islands project.
N/A, bug fix
=> Apply polyfills right away

package.json, pnpm-lock.yaml, scripts/cmd/test.js, scripts/package.json
- Remove deps from `scripts/package.json` that aren't used.
- Updated `cmd/test.js` to match Astro core (particularly parseArgs change)
This should auto close some existing renovate prs updating the unused deps.
tested manually
n/a
=> Remove unused dependencies in scripts

.github/workflows/event-dispatch.yml
Adds a workflow that listens to the event dispatch added in `withastro/astro`.
The workflow does the following:
- it extracts the commit ID sent by the event
- it checks out `withastro/astro` using the commit ID as `ref`
- it builds the whole repository
- it links the astro package
- it runs the tests for all the adapters
We should merge this PR. However I still need to fix a small bug in `withastro/astro`
N/A
=> ci: adds a workflow to listen to event dispatch

.github/workflows/event-dispatch.yml
https://github.com/withastro/adapters/actions/runs/10493012888/job/29065900246#step:12:39
This changes the workflow to run singularly the link to the astro package directly in the adapters. Doing it in at the top-level of the monorepo might not work.
I tested it locally
N/A
=> chore: build whole repo due to interconnected deps

.changeset/orange-countries-scream.md, packages/netlify/src/index.ts
Fix for: https://answers.netlify.com/t/124975/
TL;DR: The current RegEx did not match `a-us.storyblok.com` as the hostname as the RegEx only allowed lowercase letters and numbers. This PR adds `-` to the list of allowed characters.
Note that, the RegEx is not very strict. For example, as per the URL spec, the `-` should not be as the first or last character in the hostname, but this RegEx doesn't check that. It simply allows the existence of `-` in the hostname.
There's (probably) nothing much to test here.
N/A
=> fix: allow `-` in hostnames for Netlify Image CDN

.changeset/sweet-geckos-double.md, packages/cloudflare/src/index.ts, packages/netlify/src/index.ts, packages/node/src/index.ts, packages/vercel/src/serverless/adapter.ts, packages/vercel/src/static/adapter.ts
In Astro 5, the section on assets has been removed from supportedAstroFeatures because it made no sense, you cannot not support "assets" as a concept, otherwise your adapter either can't have routes (it doesn't support having an endpoint), or does not support hosting assets in general (so you don't support any imports that results in a file, no JS, no CSS, no images etc)
In truth, adapters always support `astro:assets` the feature, what they don't support is the default image service that relies on Node API at runtime. As such, options we updated to reflect only that.
N/A
N/A
=> feat: update adapters supported features to account for new shape for Astro 5

.changeset/big-countries-design.md
Add changeset so that the `send` version bump in https://github.com/withastro/adapters/pull/393 is released to fix https://github.com/withastro/adapters/issues/391
n/a
n/a
=> Add changeset for node adapter

.changeset/twenty-deers-wink.md, .changeset/weak-penguins-explode.md, packages/cloudflare/src/utils/generate-routes-json.ts, packages/cloudflare/test/fixtures/routes-json/src/reduceComplexity/env.d.ts, packages/cloudflare/test/fixtures/routes-json/src/reduceComplexity/pages/404.astro, packages/cloudflare/test/fixtures/routes-json/src/reduceComplexity/pages/dynamicPages/dynamic1.astro, packages/cloudflare/test/fixtures/routes-json/src/reduceComplexity/pages/dynamicPages/dynamic2.astro, packages/cloudflare/test/fixtures/routes-json/src/reduceComplexity/pages/dynamicPages/dynamic3.astro, packages/cloudflare/test/fixtures/routes-json/src/reduceComplexity/pages/index.astro, packages/cloudflare/test/fixtures/routes-json/src/reduceComplexity/pages/mixedPages/dynamic.astro, packages/cloudflare/test/fixtures/routes-json/src/reduceComplexity/pages/mixedPages/static.astro, packages/cloudflare/test/fixtures/routes-json/src/reduceComplexity/pages/mixedPages/subfolder/dynamic.astro, packages/cloudflare/test/fixtures/routes-json/src/reduceComplexity/pages/mixedPages/subfolder/static.astro, packages/cloudflare/test/fixtures/routes-json/src/reduceComplexity/pages/staticPages/static1.astro, packages/cloudflare/test/fixtures/routes-json/src/reduceComplexity/pages/staticPages/static2.astro, packages/cloudflare/test/fixtures/routes-json/src/reduceComplexity/pages/staticPages/static3.astro, packages/cloudflare/test/routes-json.test.js
Cloudflare has a limit of 100 includes/exclude rules. In many applications this amount is reached quite fast.
This PR add the functionality to compare include and exclude rules and reduce the amount of rules wherever possible.
Therefore it:
- adds a wildcard if a folder only belogs to include or exclude rules
- skips all subfolders where a wildcard is already present (leave them untouched)
Tested in out own project using cloudflare as well wrote a unit test here.
=> Reduce amount of rules in routes json file

.changeset/fast-penguins-build.md, packages/netlify/src/index.ts
Adds support for rewrites in Netlify edge middleware.
cc @eduardoboucas 
Fixes #412
Tested manually, because I had trouble getting e2e tests working for Netlify
=> fix(netlify): support middleware rewrite

.changeset/early-scissors-wait.md, packages/vercel/src/lib/redirects.ts, packages/vercel/test/fixtures/isr/astro.config.mjs, packages/vercel/test/fixtures/isr/src/pages/excluded/[...rest].astro, packages/vercel/test/isr.test.js
The logic for generating a match pattern ([getMatchPattern](https://github.com/withastro/adapters/blob/8274001d0d1a857e633f456c5f0ff1d469d4b6e4/packages/vercel/src/lib/redirects.ts#L46)) was initially copied from the core astro repository. Since then, the implementation in Astro Core was changed a couple of times. Here is the current implementation of this function in Astro Core: https://github.com/withastro/astro/blob/cd54210/packages/astro/src/core/routing/manifest/pattern.ts#L3.
Looking into `.vercel/output/config.json`, it was found that the route generated for the excluded path contains an extra slash. Here is an example for a `"/excluded/[...rest]"` route:
```json
...
{
"src": "^/excluded/(?:\\/(.*?))?$",
"dest": "_render"
},
...
```
However, it should look like this:
```json
...
{ …
```
=> fix: ISR opt out for routes with rest parameters

.changeset/good-rivers-add.md, packages/cloudflare/src/index.ts
**UPDATE:** I changed the approach to use a vite plugin to externalize the imports based on `resolveId`, this should be more flexible and work for all modes.
- closes https://github.com/withastro/adapters/issues/407
- I still don't know if it would work with `astro dev`, without using `wrangler`, because in a local runtime the import wouldn't work, but at least the config wouldn't complain anymore.
- existing tests
- bugfix not needed
=> chore: externalize `cloudflare:sockets` imports

.changeset/slow-mangos-call.md, packages/vercel/src/index.ts, packages/vercel/test/serverless-prerender.test.js
Closes https://github.com/withastro/adapters/issues/430
Closes PLT-2625
My latest PR that unified the adapters had a regression where the output directory couldn't be determined when `astro:config:setup` was called.
The adapter uses *known directories* that Vercel uses to deploy the assets. These directories are set when Astro triggers `astro:config:setup`, and these directories depend on `buildOutput`. **However**, in Astro v5 this value isn't the final value inside `astro:config:setup`.
For this reason, the directories are computed at the end of the build, instead. Based on that, we copy the assets to the correct folder. 
The current tests should still be valid
N/A
=> fix(vercel): output build directory

.changeset/odd-kiwis-clap.md, packages/vercel/src/serverless/adapter.ts
Add support for Node 22 on Vercel serverless. Fixes #446.
I'm not sure if this is the approach you'd like. If we have a `default` value for `status`, and Vercel uses the latest available version as the default, it seems we should've used whatever marked as `default` as the... default. Right now the code uses Node 18 instead, which is not what the `SUPPORTED_NODE_VERSIONS` constant suggests.
I considered making Node 22 the default, but I'm worried that it might be considered a breaking change.
I haven't tested it yet, don't have the time to do it right now but it seems like these changes should be enough to add the support?
The docs say
> The @astrojs/vercel adapter supports specific Node.js versions for deploying your Astro project on Vercel. To view the supported Node.js versions on …
=> fix(vercel): add support for Node 22

packages/cloudflare/package.json, packages/cloudflare/test/routes-json.test.js, packages/netlify/package.json, packages/node/package.json, packages/vercel/package.json, pnpm-lock.yaml
This PR updates **only** the peer dependency of Astro for all our adapters.
Once `5.0.0` will be published to npm, we can update also fixtures and `devDependencies`
CI should pass
N/A
=> chore: update Astro peer dep for adapters

.changeset/nine-days-grab.md, packages/cloudflare/src/index.ts
`wrangler.jsonc` support was added to Wrangler [here](https://github.com/cloudflare/workers-sdk/pull/6276) (related issue: https://github.com/cloudflare/workers-sdk/issues/5437). 
- Adds `wrangler.jsonc` to watched config files
- If `configPath` is specified in `platformProxy`, that file location is watched instead of the default config file locations.
Untested
No docs updated; I couldn’t find docs about `wrangler.json`.
=> Add support for `wrangler.jsonc`

.changeset/clever-goats-bake.md, packages/vercel/src/index.ts
fix https://github.com/withastro/adapters/issues/471
same as https://github.com/withastro/adapters/pull/447 for v7, but the changes got lost in v8
n/a
n/a
=> fix(vercel): add support for Node 22 (v8)

.changeset/great-ties-relate.md, packages/netlify/src/index.ts
Astro 5 changes the rules to prevent middleware from reassigning locals in middleware. This broke edge middleware on Netlify, because it does that to assign the Netlify context.
Tested locally and on Netlify
=> fix(netlify): don't directly assign locals

.changeset/brown-coats-dance.md, packages/cloudflare/src/index.ts, packages/netlify/src/index.ts
- Stabilizes `astro:env` secrets support
- For cloudflare, should we mark it as `limited` since secrets must be imported within request scope?
N/A
N/A
=> feat(cloudflare,netlify): stabilize astro:env secrets support

.changeset/metal-shirts-bake.md, packages/cloudflare/src/index.ts
Undo the stop gap done in https://github.com/withastro/adapters/pull/210, we no longer need this handling as it's fixed in the vue integration.
Existing tests should pass. There's a vue test.
n/a. bug fix.
=> Remove internal vue handling in cloudflare integration

.changeset/big-islands-add.md, packages/node/src/log-listening-on.ts, packages/node/src/preview.ts, packages/node/src/standalone.ts
Currently the Node adapter doesn't correctly handle the `host` option in preview.
This PR updates the adapter to use the same host rules as the astro core preview server: 
- `false` or unset uses default of `localhost`
- `true` uses wildcard host (`0.0.0.0`), meaning listen on all available host interfaces
- `undefined` (only set by using the cli flag with no argument) uses wildcard
- any other value uses that as the host
Fixes https://github.com/withastro/astro/issues/13034
Adds test suite
=> fix: correctly handle wildcard hosts in preview

.changeset/grumpy-phones-explode.md, packages/vercel/src/serverless/middleware.ts, packages/vercel/test/fixtures/middleware-with-edge-file/src/middleware.js
Vercel builds its own edge functions with the esnext target, because the Cloudflare workerd runtime they use updates v8 every week.
See [comment here](https://github.com/vercel/vercel/blob/1006f2ae9d67ea4b3cbb1073e79d14d063d42436/packages/next/scripts/build-edge-function-template.js#L20)
Also updates conditions slightly so that it also includes the workerd condition. Browser doesn't need to be manually added as it's included by default
Fixes #495
Added top level await to a edge middleware to ensure it works. It won't compile with the previous settings.
=> fix(vercel): update middleware esbuild settings

.changeset/tidy-walls-check.md, packages/vercel/package.json, packages/vercel/src/index.ts, packages/vercel/src/lib/redirects.ts, packages/vercel/test/isr.test.js, packages/vercel/test/prerendered-error-pages.test.js, packages/vercel/test/redirects.test.js, packages/vercel/test/static.test.js, pnpm-lock.yaml
This updates the Vercel adapter to use the [`@vercel/routing-utils`](https://www.npmjs.com/package/@vercel/routing-utils) to generate redirect routes, rather than building them ourselves. Instead we generate the redirects in the hgher-level path-to-regexp syntax, which we then pass to `getTransformedRoutes`. This has the benefit of automatically handling trailing slash redirects and various Vercel edge cases.
We also now validate and normalise the generated routes using `normalizeRoutes`.
This also adds an error message for conflicting config if the user has conflicting `trailingSlash` set in the Vercel config. There is no reason to use it in the `vercel.json` now, because the adapter does the same thing.
Fixes #418 
Fix #499
=> fix: use vercel routing utils

.changeset/angry-fireants-stare.md, packages/vercel/package.json, pnpm-lock.yaml
Pins version of Vercel routing utils because of https://github.com/vercel/vercel/issues/13024
Tests should now pass
=> fix: pin `@vercel/routing-utils`
